### 입력 조건
- 첫째 줄에 두 정수 N, M(4 <= N,M <= 200)이 주어집니다. 다음 N개의 줄에는 각각 M개의 정수(0 혹은 1)로 미로의 정보가 주어진다. 각각의 수들은 공백 없이 붙어서 입력으로 제시된다. 또한 시작 칸과 마지막 칸은 항상 1이다.

### 출력 조건
- 첫째 줄에 최소 이동 칸의 개수를 출력한다.

### 규칙
1. N x M 크기의 직사각형 형태의 미로
2. 시작 위치는 (1, 1)이고, 출구 위치는 (N, M), 한 번에 한 칸씩 이동
3. 괴물이 있는 부분은 0, 괴물이 없는 부분은 1

### ex)
- 입력 
    - 5 6
    - 1 0 1 0 1 0
    - 1 1 1 1 1 1 
    - 0 0 0 0 0 1
    - 1 1 1 1 1 1
    - 1 1 1 1 1 1
 
- 출력 
    - 10

In [35]:
# 미로 크기
n, m = map(int, input().split())

# 미로
Map = []
for i in range(n):
    Map.append(list(map(int, input())))

5 6
101010
111111
000001
111111
111111


In [36]:
from collections import deque
import numpy as np

# 이동 좌표
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]

def bfs(x, y):
    queue = deque() # 큐 생성
    queue.append((x, y)) # 최초 노드 삽압
    
    while queue: # 큐에 요소가 없을 때까지 동작
        x, y = queue.popleft() # 노드 꺼낸다
        for i in range(4):
            nx = x + dx[i] # 인접 노드 좌표
            ny = y + dy[i]
            
            if nx < 0 or nx >= n or ny <0 or ny >= m: # 인접 노드 좌표가 미로 크기를 벗어나면 종료
                continue
            
            if Map[nx][ny] == 0: # 인접 노드 좌표의 값이 0이면 종료
                continue
            
            if Map[nx][ny] == 1: # 인접 노드 좌표의 값이 1이면 
                Map[nx][ny] = Map[x][y] + 1 # # 인접 노드 좌표의 값 업데이트
                print(np.array(Map), '\n')
                queue.append((nx, ny)) # 큐에 해당 좌표 삽입
    return Map[n-1][m-1] # 마지막 칸 값 리턴 

In [37]:
bfs(0,0)

[[1 0 1 0 1 0]
 [2 1 1 1 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 1 0 1 0]
 [2 1 1 1 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 1 0 1 0]
 [2 3 1 1 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 1 0 1 0]
 [2 3 4 1 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 1 0]
 [2 3 4 1 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 1 0]
 [2 3 4 5 1 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 1 0]
 [2 3 4 5 6 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 7 0]
 [2 3 4 5 6 1]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 7 0]
 [2 3 4 5 6 7]
 [0 0 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 7 0]
 [2 3 4 5 6 7]
 [0 0 0 0 0 8]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 

[[3 0 5 0 7 0]
 [2 3 4 5 6 7]
 [0 0 0 0 0 8]
 [1 1 1 1 1 9]
 [1 1 1 1 1 1]] 

[[ 3  0  5  0  7  0]
 [ 2  3  4  5  6  7]
 [ 0  0  0  0  0  8]
 [ 1  1  1  1  1  9]
 [ 1  1  1  1  1 10]] 

[[ 3  0  5  0  7  0]
 [ 2  3  4  5

10

In [38]:
Map

[[3, 0, 5, 0, 7, 0],
 [2, 3, 4, 5, 6, 7],
 [0, 0, 0, 0, 0, 8],
 [14, 13, 12, 11, 10, 9],
 [15, 14, 13, 12, 11, 10]]