### 입력 조건
- 첫째 줄에 맵의 세로 크기 N과 가로 크기 M을 공백으로 구분하여 입력한다. (3 <= N,M <=50)
- 둘째 줄에 게임 캐릭터가 있는 칸의 좌표 (A, B)와 바라보는 방향 d가 각각 서로 공백으로 구분하여 주어진다. 방향 d의 값으로는 다음과 같이 4가지가 존재한다.
    - 0: 북쪽, 1: 동쪽, 2: 남쪽, 3: 서쪽
- 셋째 줄부터 맵이 육지인지 바다인지에 대한 정보가 주어진다. N개의 줄에 맵의 상태가 북쪽부터 남쪽 순서대로, 각 줄의 데이터는 서쪽부터 동쪽 순서대로 주어진다. 맵의 외곽은 항상 바다로 되어 있다.
    - 0: 육지, 1: 바다
- 처음에 게임 캐릭터가 위치한 칸의 상태는 항상 육지이다.

### 출력 조건
- 첫째 줄에 이동을 마친 후 캐릭터가 방문한 칸의 수를 출력한다.

### 규칙
1. 캐릭터가 있는 장소는 1 X 1 크기의 정사각형으로 이뤄진 N X M 크기의 직사각형으로, 각각의 칸은 육지 또는 바다이다. 캐릭터는 동서남북 중 한 곳을 바라본다
2. 맵의 각 칸은 (A, B)로 나타낼 수 있고, A는 북쪽으로부터 떨어진 칸의 개수, B는 서쪽으로부터 떨어진 칸의 개수이다.
3. 캐릭터는 상하좌우로 움직일 수 있고, 바다로 되어 있는 공간에는 갈 수 없다. 

캐릭터 움직임
1. 현재 위치에서 현재 방향을 기준으로 왼쪽 방향(반시계 방향으로 90도 회전한 방향)부터 차례대로 갈 곳을 정한다.
2. 캐릭터의 바로 왼쪽 방향에 아직 가보지 않은 칸이 존재한다면, 왼쪽 방향으로 회전한 다음 왼쪽으로 한 칸을 전진한다. 왼쪽 방향에 가보지 않은 칸이 없다면, 왼쪽 방향으로 회전만 수행하고 1단계로 돌아간다.
3. 만약 네 방향 모두 이미 가본 칸이거나 바다로 되어 있는 칸인 경우에는, 바라보는 방향을 유지한 채로 한 칸 뒤로 가고 1단계로 돌아간다. 단, 이때 뒤쪽 방향이 바다인 칸이라 뒤로 갈 수 없는 경우에는 움직임을 멈춘다. 

### ex)
- 입력
    - 4 4
    - 1 1 0
    - 1 1 1 1 
    - 1 0 0 1
    - 1 1 0 1
    - 1 1 1 1 
- 출력
    - 3

In [46]:
import numpy as np

In [47]:
# 맵 크기
n, m = map(int, input().split())

# 현재 위치, 방향
x, y, d = map(int, input().split())

# 맵 생성
Map = []
for i in range(n):
    Map.append(list(map(int, input().split())))

np.array(Map)

4 4 
1 1 0
1 1 1 1
1 0 0 1
1 1 0 1
1 1 1 1


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 1]])

In [48]:
# 방문 기록할 맵 생성
count_map = [[0]*m for _ in range(n)]

# 시작 위치 방문 표시
count_map[x][y] = 1

np.array(count_map)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
# 방문 칸 수(시작 위치 1칸 세고 시작)
count = 1

# 회전 횟수
turn_count = 0

# 이동 좌표(북, 동, 남, 서)
dx = [-1, 0, 1, 0]
dy = [0, 1, 0, -1]

# 갈 곳이 없을 때 까지 반복
while True:
    # 왼쪽 회전
    d -= 1 # 왼쪽으로 회전 북 -> 서 -> 남 -> 동
    if d == -1: # 북 -> 서
        d = 3
        
    # 정면 좌표
    new_x = x + dx[d]
    new_y = y + dy[d]
    
    # 육지이고 방문하지 않았다면
    if Map[new_x][new_y] == 0 and count_map[new_x][new_y] == 0:
        
        # 이동(좌표 업데이트)
        x = new_x
        y = new_y
        
        # 방문 했다고 표시
        count_map[new_x][new_y] = 1
        
        # 방문 칸 수 증가
        count += 1
        
        # 회전 횟수 초기화
        turn_count = 0
        
        continue
        
    # 바다거나 방문 했다면    
    else:
        # 회전 횟수 증가
        turn_count += 1
        
    # 모든 방향으로 회전했다면
    if turn_count == 4:
        # 회전 횟수 초기화 
        turn_count = 0
        
        # 후면 좌표
        new_x = x - dx[d]
        new_y = y - dy[d]
        
        # 후면 좌표가 육지라면
        if Map[new_x][new_y] == 0:
            # 이동(좌표 업데이트)
            x = new_x
            y = new_y
        
        # 바다라면
        else:
            break
            
print(count, '\n')
print(np.array(Map), '\n')
print(np.array(count_map))

3 

[[1 1 1 1]
 [1 0 0 1]
 [1 1 0 1]
 [1 1 1 1]] 

[[0 0 0 0]
 [0 1 1 0]
 [0 0 1 0]
 [0 0 0 0]]
